In [60]:
import pandas as pd
import os

In [ ]:
df = pd.read_csv("/content/IndianFoodDatasetCSV.csv")

In [ ]:
df.drop(columns=['Srno', 'RecipeName', 'Ingredients', 'PrepTimeInMins', 'CookTimeInMins', 'Servings', 'Cuisine', 'Course', 'Diet', 'Instructions', 'URL'], inplace=True)

In [ ]:
df.dropna()

,TranslatedRecipeName,TranslatedIngredients,TotalTimeInMins,TranslatedInstructions
0,Masala Karela Recipe,"6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...",45,"To begin making the Masala Karela Recipe,de-se..."
1,Spicy Tomato Rice (Recipe),"2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...",15,"To make tomato puliogere, first cut the tomato..."
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...",50,"To begin making the Ragi Vermicelli Recipe, fi..."
3,Gongura Chicken Curry Recipe - Andhra Style Go...,"500 grams Chicken,2 Onion - chopped,1 Tomato -...",45,To begin making Gongura Chicken Curry Recipe f...
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"1 tablespoon chana dal, 1 tablespoon white ura...",30,"To make Andhra Style Alam Pachadi, first heat ..."
...,...,...,...,...
6866,Goan Mushroom Xacuti Recipe,"20 बटन मशरुम,2 प्याज - काट ले,1 टमाटर - बारीक ...",60,गोअन मशरुम जकुटी रेसिपी बनाने के लिए सबसे पहले...
6867,Sweet Potato & Methi Stuffed Paratha Recipe,"1 बड़ा चम्मच तेल,1 कप गेहूं का आटा,नमक - स्वाद ...",90,शकरकंदी और मेथी का पराठा रेसिपी बनाने के लिए स...
6868,Ullikadala Pulusu Recipe | Spring Onion Curry,150 grams Spring Onion (Bulb & Greens) - chopp...,15,To begin making Ullikadala Pulusu Recipe | Spr...
6869,Kashmiri Style Kokur Yakhni Recipe-Chicken Coo...,"1 kg Chicken - medium pieces,1/2 cup Mustard o...",75,To begin making the Kashmiri Kokur Yakhni reci...
6870,Navrang Dal Recipe,"2 बड़े चम्मच हरी मूंग दाल,2 बड़े चम्मच सफ़ेद उरद ...",40,नवरंग दाल रेसिपी बनाने के लिए सबसे पहले सारी ...

In [ ]:
df.to_csv('indian_recipe.csv')

In [ ]:
def contains_hindi(text):
    for char in text:
        if '\u0900' <= char <= '\u097F':
            return True
    return False

In [ ]:
cols = [
    "TranslatedRecipeName",
    "TranslatedIngredients",
    "TranslatedInstructions"
]

In [ ]:
df['has_hindi'] = df.apply(lambda row: any(contains_hindi(str(row[col])) for col in cols), axis=1)

In [ ]:
df['has_hindi'].value_counts()

has_hindi
False    6036
True      835
Name: count, dtype: int64

In [ ]:
df = df[df['has_hindi'] == False]

In [ ]:
df.head()

,TranslatedRecipeName,TranslatedIngredients,TotalTimeInMins,TranslatedInstructions,has_hindi
0,Masala Karela Recipe,"6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...",45,"To begin making the Masala Karela Recipe,de-se...",False
1,Spicy Tomato Rice (Recipe),"2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...",15,"To make tomato puliogere, first cut the tomato...",False
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...",50,"To begin making the Ragi Vermicelli Recipe, fi...",False
3,Gongura Chicken Curry Recipe - Andhra Style Go...,"500 grams Chicken,2 Onion - chopped,1 Tomato -...",45,To begin making Gongura Chicken Curry Recipe f...,False
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"1 tablespoon chana dal, 1 tablespoon white ura...",30,"To make Andhra Style Alam Pachadi, first heat ...",False

In [ ]:
df['has_hindi'].value_counts()

has_hindi
False    6036
Name: count, dtype: int64

In [ ]:
df.drop(columns=['has_hindi'], inplace=True)

/tmp/ipykernel_1236/3413682235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['has_hindi'], inplace=True)

In [ ]:
df.to_csv('indian_recipe.csv')

In [104]:
df = pd.read_csv('indian_recipe.csv')

In [105]:
df.head()

,Unnamed: 0,TranslatedRecipeName,TranslatedIngredients,TotalTimeInMins,TranslatedInstructions
0,0,Masala Karela Recipe,"6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...",45,"To begin making the Masala Karela Recipe,de-se..."
1,1,Spicy Tomato Rice (Recipe),"2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...",15,"To make tomato puliogere, first cut the tomato..."
2,2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...",50,"To begin making the Ragi Vermicelli Recipe, fi..."
3,3,Gongura Chicken Curry Recipe - Andhra Style Go...,"500 grams Chicken,2 Onion - chopped,1 Tomato -...",45,To begin making Gongura Chicken Curry Recipe f...
4,4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"1 tablespoon chana dal, 1 tablespoon white ura...",30,"To make Andhra Style Alam Pachadi, first heat ..."

In [106]:
df.drop(columns=['Unnamed: 0', 'TotalTimeInMins'], inplace=True)

In [107]:
df['TranslatedRecipeName'] = (
    df['TranslatedRecipeName']
    .str.replace(r'\(recipe\)|\brecipe\b', ' ', case=False, regex=True) # Remove words
    .str.replace(r'\s+', ' ', regex=True)                             # Collapse multiple spaces into one
    .str.strip()                                                     # Remove leading/trailing spaces
)

In [108]:
df.head()

,TranslatedRecipeName,TranslatedIngredients,TranslatedInstructions
0,Masala Karela,"6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...","To begin making the Masala Karela Recipe,de-se..."
1,Spicy Tomato Rice,"2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...","To make tomato puliogere, first cut the tomato..."
2,Ragi Semiya Upma - Ragi Millet Vermicelli Brea...,"1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...","To begin making the Ragi Vermicelli Recipe, fi..."
3,Gongura Chicken Curry - Andhra Style Gongura C...,"500 grams Chicken,2 Onion - chopped,1 Tomato -...",To begin making Gongura Chicken Curry Recipe f...
4,Andhra Style Alam Pachadi - Adrak Chutney,"1 tablespoon chana dal, 1 tablespoon white ura...","To make Andhra Style Alam Pachadi, first heat ..."

In [112]:
df.to_csv('indian_recipe.csv')

In [109]:
df["text"] = df.apply(
    lambda row: (
        f"Recipe: {row['TranslatedRecipeName']}\n\n"
        f"Ingredients:\n{row['TranslatedIngredients']}\n\n"
        f"Instructions:\n{row['TranslatedInstructions']}"
    ),
    axis=1
)

In [113]:
df.head()

,TranslatedRecipeName,TranslatedIngredients,TranslatedInstructions,text
0,Masala Karela,"6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...","To begin making the Masala Karela Recipe,de-se...",Recipe: Masala Karela\n\nIngredients:\n6 Karel...
1,Spicy Tomato Rice,"2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...","To make tomato puliogere, first cut the tomato...",Recipe: Spicy Tomato Rice\n\nIngredients:\n2-1...
2,Ragi Semiya Upma - Ragi Millet Vermicelli Brea...,"1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...","To begin making the Ragi Vermicelli Recipe, fi...",Recipe: Ragi Semiya Upma - Ragi Millet Vermice...
3,Gongura Chicken Curry - Andhra Style Gongura C...,"500 grams Chicken,2 Onion - chopped,1 Tomato -...",To begin making Gongura Chicken Curry Recipe f...,Recipe: Gongura Chicken Curry - Andhra Style G...
4,Andhra Style Alam Pachadi - Adrak Chutney,"1 tablespoon chana dal, 1 tablespoon white ura...","To make Andhra Style Alam Pachadi, first heat ...",Recipe: Andhra Style Alam Pachadi - Adrak Chut...

In [114]:
df.drop(columns=['TranslatedRecipeName', 'TranslatedIngredients', 'TranslatedInstructions'], inplace=True)

In [115]:
df.head()

                                                text
0  Recipe: Masala Karela\n\nIngredients:\n6 Karel...
1  Recipe: Spicy Tomato Rice\n\nIngredients:\n2-1...
2  Recipe: Ragi Semiya Upma - Ragi Millet Vermice...
3  Recipe: Gongura Chicken Curry - Andhra Style G...
4  Recipe: Andhra Style Alam Pachadi - Adrak Chut...

In [118]:
df['text'][0]

'Recipe: Masala Karela\n\nIngredients:\n6 Karela (Bitter Gourd/ Pavakkai) - deseeded,Salt - to taste,1 Onion - thinly sliced,3 tablespoon Gram flour (besan),2 teaspoons Turmeric powder (Haldi),1 tablespoon Red Chilli powder,2 teaspoons Cumin seeds (Jeera),1 tablespoon Coriander Powder (Dhania),1 tablespoon Amchur (Dry Mango Powder),Sunflower Oil - as required\n\nInstructions:\nTo begin making the\xa0Masala Karela Recipe,de-seed the karela and slice. Do not remove the skin as the skin has all the nutrients.\xa0Add the karela to the pressure cooker with 3 tablespoon of water, salt and turmeric powder and pressure cook for three whistles. Release the pressure immediately and open the lids. Keep aside.Heat oil in a heavy bottomed pan or a kadhai. Add cumin seeds and let it sizzle.Once the cumin seeds have sizzled, add onions and saute them till it turns golden brown in color.Add the karela,\xa0red chilli powder, amchur powder, coriander powder and besan. Stir to combine the masalas into the karela.Drizzle a little extra oil on the top and mix again. Cover the pan and simmer\xa0Masala Karela stirring occasionally until everything comes together well. Turn off the heat.Transfer\xa0Masala Karela into a serving bowl and serve.Serve\xa0Masala Karela\xa0along with\xa0Panchmel Dal\xa0and\xa0Phulka\xa0for a weekday meal with your family.\xa0'

In [121]:
df['text'] = (df['text']
    .str.replace(r'\xa0', ' ', regex=True) # Remove \xa0
    .str.replace(r'\s+', ' ', regex=True)                             # Collapse multiple spaces into one
    .str.strip()                                                     # Remove leading/trailing spaces
)

In [123]:
df['text'][0]

'Recipe: Masala Karela Ingredients: 6 Karela (Bitter Gourd/ Pavakkai) - deseeded,Salt - to taste,1 Onion - thinly sliced,3 tablespoon Gram flour (besan),2 teaspoons Turmeric powder (Haldi),1 tablespoon Red Chilli powder,2 teaspoons Cumin seeds (Jeera),1 tablespoon Coriander Powder (Dhania),1 tablespoon Amchur (Dry Mango Powder),Sunflower Oil - as required Instructions: To begin making the Masala Karela Recipe,de-seed the karela and slice. Do not remove the skin as the skin has all the nutrients. Add the karela to the pressure cooker with 3 tablespoon of water, salt and turmeric powder and pressure cook for three whistles. Release the pressure immediately and open the lids. Keep aside.Heat oil in a heavy bottomed pan or a kadhai. Add cumin seeds and let it sizzle.Once the cumin seeds have sizzled, add onions and saute them till it turns golden brown in color.Add the karela, red chilli powder, amchur powder, coriander powder and besan. Stir to combine the masalas into the karela.Drizzle a little extra oil on the top and mix again. Cover the pan and simmer Masala Karela stirring occasionally until everything comes together well. Turn off the heat.Transfer Masala Karela into a serving bowl and serve.Serve Masala Karela along with Panchmel Dal and Phulka for a weekday meal with your family.'

In [124]:
df.to_csv('indian_recipe_single_text.csv')

In [2]:
df = pd.read_csv('indian_recipe_single_text.csv')

In [4]:
df['text'][0]

'Recipe: Masala Karela Ingredients: 6 Karela (Bitter Gourd/ Pavakkai) - deseeded,Salt - to taste,1 Onion - thinly sliced,3 tablespoon Gram flour (besan),2 teaspoons Turmeric powder (Haldi),1 tablespoon Red Chilli powder,2 teaspoons Cumin seeds (Jeera),1 tablespoon Coriander Powder (Dhania),1 tablespoon Amchur (Dry Mango Powder),Sunflower Oil - as required Instructions: To begin making the Masala Karela Recipe,de-seed the karela and slice. Do not remove the skin as the skin has all the nutrients. Add the karela to the pressure cooker with 3 tablespoon of water, salt and turmeric powder and pressure cook for three whistles. Release the pressure immediately and open the lids. Keep aside.Heat oil in a heavy bottomed pan or a kadhai. Add cumin seeds and let it sizzle.Once the cumin seeds have sizzled, add onions and saute them till it turns golden brown in color.Add the karela, red chilli powder, amchur powder, coriander powder and besan. Stir to combine the masalas into the karela.Drizzle a little extra oil on the top and mix again. Cover the pan and simmer Masala Karela stirring occasionally until everything comes together well. Turn off the heat.Transfer Masala Karela into a serving bowl and serve.Serve Masala Karela along with Panchmel Dal and Phulka for a weekday meal with your family.'

In [61]:
HF_TOKEN = os.environ.get("HF_TOKEN")

In [16]:
import requests

# 1. Replace with your actual token from Hugging Face
# MODEL_ID = "BAAI/bge-small-en-v1.5"
MODEL_ID = "BAAI/bge-m3"
# API_URL = f"https://router.huggingface.co/hf-inference/models/{MODEL_ID}"
API_URL= f"https://router.huggingface.co/hf-inference/models/{MODEL_ID}/pipeline/feature-extraction"

def get_embeddings_batch(text_list):
    """Sends a list of texts to the API and returns a list of vectors."""
    headers = {
        "Authorization": f"Bearer {HF_TOKEN}",
        "Content-Type": "application/json",
        "X-Wait-For-Model": "true" # Forces the API to load the model if it's idle
    }
    payload = {
        "inputs": text_list,
        # "options": {"wait_for_model": True}
    }
    response = requests.post(API_URL, headers=headers, json=payload)

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error {response.status_code}: {response.text}")
        return None

In [10]:
temp_text = df['text'][:9].tolist()

In [17]:
vectors = get_embeddings_batch(temp_text)

In [21]:
len(vectors)

9

In [26]:
import time

# --- BATCH EXECUTION ---
batch_size = 10
embedding_vectors = []

# Assuming your combined text is in a column named 'text'
text_data = df['text'].tolist()

print(f"Starting batch embedding for {len(text_data)} recipes...")

for i in range(0, len(text_data), batch_size):
    batch = text_data[i : i + batch_size]
    vectors = get_embeddings_batch(batch)

    if vectors:
        embedding_vectors.extend(vectors)
    else:
        # If a batch fails, we add None to keep the list length consistent
        embedding_vectors.extend([None] * len(batch))

    # Optional: Brief pause to be nice to the API
    time.sleep(0.1)

# Add the vectors back to your original DataFrame
# df['embedding'] = embedding_vectors

Starting batch embedding for 6036 recipes...

In [28]:
len(embedding_vectors[0])

1024

In [62]:
QD_API_KEY = os.environ.get("QD_API_KEY")

In [30]:
QD_URL = "https://cf70a57d-9ec4-4c3e-808e-df9c59623fa8.sa-east-1-0.aws.cloud.qdrant.io"

In [48]:
!pip install --upgrade qdrant-client

Requirement already satisfied: qdrant-client in /usr/local/lib/python3.12/dist-packages (1.17.1)
Requirement already satisfied: grpcio>=1.41.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (1.80.0)
Requirement already satisfied: httpx>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]>=0.20.0->qdrant-client) (0.28.1)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (2.0.2)
Requirement already satisfied: portalocker<4.0,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (3.2.0)
Requirement already satisfied: protobuf>=3.20.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (5.29.6)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (2.12.3)
Requirement already satisfied: urllib3<3,>=1.26.14 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (2.5.0)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio>=1.41.0->qdrant-client) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]>=0.20.0->qdrant-client) (4.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client) (0.4.2)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client) (4.1.0)

In [23]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
import uuid

In [31]:
#initializing the client to qdrant
client = QdrantClient(
    url=QD_URL,
    api_key=QD_API_KEY
)

In [32]:
client.recreate_collection(
    collection_name="indian_recipes",
    vectors_config = VectorParams(size=1024, distance=Distance.COSINE)
)

/tmp/ipykernel_5052/537525570.py:1: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  client.recreate_collection(

True

In [33]:
#converting the text and vector pairs into points to add to qdrant
point = []
for text_val, vector_val in zip(text_data, embedding_vectors):
  if vector_val is not None:
    point.append(
        PointStruct(
            id=str(uuid.uuid4()), #generating unique id as strings
            vector=vector_val,
            payload={
                "recipe": text_val #storing the full recipe
            }
        )
    )

In [38]:
len(point)

6036

In [39]:
# 3. Push to Qdrant in a loop in batches of 100
batch_size = 200
for i in range(0,len(point),batch_size):
  batch = point[i : i + batch_size]

  client.upsert(
      collection_name="indian_recipes",
      points=batch
  )

In [40]:
query = "how to make masala karela"

In [43]:
def get_embedding(text):
  headers = {
        "Authorization": f"Bearer {HF_TOKEN}",
        "Content-Type": "application/json",
        "X-Wait-For-Model": "true" # Forces the API to load the model if it's idle
    }
  payload = {
      "inputs": text,
      # "options": {"wait_for_model": True}
  }
  response = requests.post(API_URL, headers=headers, json=payload)

  if response.status_code == 200:
      return response.json()
  else:
      print(f"Error {response.status_code}: {response.text}")
      return None

In [44]:
query_embedding = get_embedding(query)

In [50]:
hits = client.query_points(
    collection_name="indian_recipes",
    query=query_embedding,
    limit=3
)

In [59]:
hits.points[1].payload['recipe']

'Recipe: Bitter gourd spice vegetable Ingredients: 3 Karela (Bitter Gourd/ Pavakkai) - cut into thin wedges with seeds removed,1 Onion - thinly sliced,2 cloves Garlic - grated,1 inch Ginger - grated,2 Tomatoes - finely chopped or pureed,1 teaspoon Turmeric powder (Haldi),1 teaspoon Amchur (Dry Mango Powder),1 teaspoon Garam masala powder,1 teaspoon Coriander Powder (Dhania),Salt - to taste,Red Chilli powder - to taste,1 teaspoon Jaggery - or sugar,Sunflower Oil - for cooking Instructions: To begin making the Karela Masala Sabzi Recipe, we will first cook the karela in the pressure cooker. You can also steam it in your steamer if you wish.Place the karela in the pressure cooker; add in 2 or 3 tablespoons of water, sprinkle some salt and some turmeric powder. Give it a stir.Cover the cooker and pressure cook until you hear just one whistle. Turn off the heat and release the pressure immediately by placing the cooker under tap water. This releases the pressure immediately. Watch the video recipe of how to cook vegetables in a pressure cookerOnce the karela is cooked, we will proceed to make the masala.Heat 2 tablespoons of oil in a heavy bottomed pan; add in the onions, ginger and garlic in the pan.Saute on low to medium heat until the onions have become tender and the raw smell goes away.Once the onions are tender, add in the tomatoes and the remaining masalas, including amchur masala, garam masala,dhania powder, salt and red chilli powder.Stir fry until the tomatoes are partially cooked. Next add in the steamed karela, check for the salt and spice levels and adjust to suit your taste.Cover the pan; turn the heat to low and cook the karela along with its masala for about 10 minutes until the karela is soft and well coated with the masala.Once done, add in the chopped coriander leaves and turn off the heat. Transfer the Karela Masala Sabzi into a serving bowl.Serve the Karela Masala Sabzi along with Panchmel Dal, Palak Raita and Phulka for an everyday meal.'